//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcExceptionHandleLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSCODE
    {
        public string CODE_ID { get; set; }
        public string CKIND { get; set; }
        public string CODE_NO { get; set; }
        public string CODE_NAME { get; set; }
        public string DESCTXT { get; set; }
        public string ENABLED { get; set; }
        public Nullable<int> ORDERNUM { get; set; }
        public string COMP_NO { get; set; }
        public string DEP_NO { get; set; }
        public string DEL_CODE { get; set; }
    
        public virtual SYSCKIND SYSCKIND { get; set; }
    }
}
